name: common CI
on: workflow_call
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo Build

  Test: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo Test

  Deploy: 
    runs-on: ubuntu-latest
    needs: Test
    steps:  
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo build