name: common CI
on: 
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo Build

  Test: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo Test

  Dev-deployment: 
    runs-on: ubuntu-latest
    needs: Test
    steps:  
      - name: checkout repo code
        uses: actions/checkout@v4
        with:
          repository: raghudevops83/roboshop-helm
      - name: Deploy
        run: make component=${{inputs.component_name}} env=dev